### ISSUE TITLE
Gmail の内容を Slack 通知したい

### ISSUE THREAD

**Issue by laughk** [laughk/TIL#10]
[(第99回)Python mini Hack-a-thon - connpass](https://pyhack.connpass.com/event/127299/)

いろいろ調べながら試行錯誤することになりそうなので Issue にしとく
とりあえず以下のことやりたい

- 色々事情があって、一部自分に飛んでくる mail を家庭 Slack に通知したい
- Gmail ( GCP? ) の API を上手く使ってよしなにしたい
- とりあえず Slack には incoming webhook で雑に投げ込めればよい。

**Comment by laughk** [comment]
# 参考になりそうなリンク

- [Gmail APIとPub/Subでリアルタイムメール受信 on ruby - Qiita](https://qiita.com/1ulce/items/672ae85d8c23bd9c478e)

### GCP Cloud functions 

- [Cloud Functions の呼び出し  |  Cloud Functions のドキュメント  |  Google Cloud](https://cloud.google.com/functions/docs/calling/?hl=ja)

> Gmail Push Notification API をお使いいただくことで、Gmail イベントを Cloud Pub/Sub トピックに送り、Cloud Functions と一緒に呼び出すことができます。

### Gmail の API

- https://developers.google.com/gmail/api/quickstart/python

**Comment by laughk** [comment]
:eyes:   この辺にサンプルがある

https://github.com/gsuitedevs/python-samples/tree/master/gmail

**Comment by laughk** [comment]
:thought_balloon: quickstart.py は Gmail の label 一覧を表示するやつっぽい

**Comment by laughk** [comment]
初回起動の際に認証を求められた

**Comment by laughk** [comment]
cloud functions に乗っけるスクリプトには CLI モードを有効にしてローカルでデバッグ、行けそうなら cloud functions へデプロイという感じでいいだろうか。

**Comment by laughk** [comment]
この辺をいじればやりたいことができるかも？

https://github.com/gsuitedevs/python-samples/blob/master/gmail/quickstart/quickstart.py#L49-L53

**Comment by laughk** [comment]
Gmail の API にどうアクセスしていくかのイメージが Quickstart だけだと掴めなかったけどここの記事のコードでちょっとイメージできたかも。

ref. [Pythonを使ってGmail APIからメールを取得する - Qiita](https://qiita.com/orikei/items/73dc1ccc95d1872ab1cf)

**Comment by laughk** [comment]
例えば特定の人とのやり取りと取りたい時

```python
    query = '(from OR to OR cc):u****@*******.co.jp'
    results = service.users()\
        .messages()\
        .list(userId='me', q=query)\
        .execute()
    print(results)
```

結果 (雰囲気)

```python
{
  'messages': [{'id': '16*********', 'threadId': '16************'},
              {'id': '16*********', 'threadId': '16************'},
              {'id': '16*********', 'threadId': '16************'},
              {'id': '16*********', 'threadId': '16************'},
              {'id': '16*********', 'threadId': '16************'},
              {'id': '16*********', 'threadId': '16************'},
              {'id': '16*********', 'threadId': '16************'},
              {'id': '16*********', 'threadId': '16************'},
              {'id': '16*********', 'threadId': '16************'}],
 'resultSizeEstimate': 23
}
```

ここまでだと、あくまで個別にアクセスするための ID 情報だけが取れるっぽい

**Comment by laughk** [comment]
特定のメッセージのとり方

[Users.messages: get  |  Gmail API  |  Google Developers](https://developers.google.com/gmail/api/v1/reference/users/messages/get)

**Comment by laughk** [comment]
message.get したときのレスポンス

[Users.messages  |  Gmail API  |  Google Developers](https://developers.google.com/gmail/api/v1/reference/users/messages#resource)

**Comment by laughk** [comment]
snippet だとメッセージ本文全体が取れないんだよなー
payload.body からじゃないとダメそう

**Comment by laughk** [comment]
payload.body, base64url って形式で encode されてるみたい

https://developers.google.com/gmail/api/v1/reference/users/messages/attachments#resource

> The body data of a MIME message part as a base64url encoded string. May be empty for MIME container types that have no message body or when the body data is sent as a separate attachment. An attachment ID is present if the body data is contained in a separate attachment.

**Comment by laughk** [comment]
なんか文字コード壊れてる... ? なんか上手く decode できない :sob: 

- base64 -> bytes :ok_woman: 
- bytes -> utf-8 (str) :dizzy_face: 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/encodings/utf_8_sig.py", line 23, in decode
    (output, consumed) = codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 12-13: invalid continuation byte
```

ちなみに `.decode('utf-8', 'ignore') してみるも、ほとんどがぐっちゃぐちゃで読めたものではない...

**Comment by laughk** [comment]
> なんか文字コード壊れてる... ? なんか上手く decode できない sob

base64url が曲者だったっぽい。
https://github.com/ploopkazoo/python-base64url/blob/master/base64url.py のコードを一部流用させてもらったら行けそうな気配。

body_data に payload.body.data が入ってる前提

### before

```python
            try:
                body_64decoded = base64.b64decode(body_data)
                print(f'payload.body.data(64decoded): {body_64decoded}')
            except:
                print(f'payload.body.data(64decoded): (passed)')

            try:
                body_decoded = bytes(body_64decoded).decode()
                print(f'payload.body.data(decoded): {body_decoded}')
            except:
                print(f'payload.body.data(decoded): (passed)')

```

### after 

```python
            try:
                body_64decoded = base64.b64decode(base64urldecode(body_data))
                print(f'payload.body.data(64decoded): {body_64decoded}')
            except:
                print(f'payload.body.data(64decoded): (passed)')

            try:
                body_decoded = bytes(body_64decoded).decode()
                print(f'payload.body.data(decoded): {body_decoded}')
            except:
                print(f'payload.body.data(decoded): (passed)')

```

**Comment by laughk** [comment]
> https://github.com/ploopkazoo/python-base64url/blob/master/base64url.py のコードを一部流用させてもらったら行けそうな気配。

公式ライブラリでこのへんやってくれるのがあるらしいので調べて差し替える

**Comment by laughk** [comment]
> 公式ライブラリでこのへんやってくれるのがあるらしいので調べて差し替える

@HayaoSuzuki が教えてくれた thx!!

https://docs.python.org/ja/3/library/base64.html#base64.urlsafe_b64decode

ref. https://twitter.com/CardinalXaro/status/1132213056098820101

**Comment by laughk** [comment]
Webhook が最近新しいものが出てきている。

- [slackのIncoming webhookが新しくなっていたのでまとめてみた - Qiita](https://qiita.com/kshibata101/items/0e13c420080a993c5d16)

これが結構ややこしい。形式は以下のツールで色々手探りしてる
https://api.slack.com/tools/block-kit-builder

https://github.com/laughk/TIL/blob/0cd7906efcfa97cfd2b44099a707d89ec303f494/gmail_tool/modules/fetch.py#L35-L57
